class AlreadyRunningError(Exception):
    pass

class NotRunningError(Exception):
    pass
